apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmmm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-bbb
  template:
    metadata:
      labels:
        app: report-bbb
    spec:
      containers:
        - image: burja8x/rso3:9.1
          name: report-bbb
          env:
            - name: APP_CONFIG_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: config-conn-string
                  key: app-config-conn-string
            - name: hello1
              value: 589347956834976fsag
          ports:
            - containerPort: 80
              name: server-http
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: report-bbb
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: server-http
  selector:
    app: report-bbb